### ISSUE TITLE
Usage of os.uptime()

### ISSUE THREAD

**Issue by sonicdoe** [oroce/node-os-uptime#1]
Is there a specific reason why this package doesn’t use [Node.js’s native `os.uptime()`](https://nodejs.org/api/os.html#os_os_uptime) method?

**Comment by oroce** [comment]
@sonicdoe yes there is. os.uptime() returns the elapsed seconds since the system has been up, i wanted a datetime. 

of course i could have just done `new Date(Date.now() - os.uptime())`, but on rasperry pi as i was reporting the uptime every 5 minutes I struggled with v8 pauses, so it was reporting different date everytime (couple of ms diff) and change detection mechanism I used was generating false positive reports. :(

**Comment by sonicdoe** [comment]
Thanks, good to know. Would you be open to a pull request which mentions `os.uptime()` in the README?

**Comment by oroce** [comment]
of course, that would be lovely.
